/**
 * App.tsx 叶子路由的可执行清单。
 *
 * 路由结构仍以 App.tsx 为运行时真源；配套单测用 TypeScript AST 将两者逐项比对，
 * 因而新增路由若未登记（或守卫、重定向语义改变）会 fail closed。
 */
export type AppRouteAccess = 'public' | 'protected';
export type AppRouteKind = 'page' | 'redirect' | 'resolver_redirect' | 'not_found';
export type AppRoutePermission =
  'anonymous' | 'authenticated' | 'human' | 'workspace_admin' | 'workspace_owner';

export type BrowserVerification =
  | { readonly level: 'core' }
  | {
      readonly level: 'extended';
      readonly readySelector: string;
      /** 公开但登录后才呈现完整正常态的页面（设备授权）。 */
      readonly authenticated?: boolean;
      /** resolver/OAuth 成功后允许落到的规范路径；缺省为 samplePath 自身。 */
      readonly expectedPath?: string;
    }
  | { readonly level: 'redirect'; readonly expectedPath: string };

export interface AppRouteManifestEntry {
  readonly id: string;
  readonly pattern: string;
  readonly samplePath: string;
  readonly element: string;
  readonly access: AppRouteAccess;
  readonly permission: AppRoutePermission;
  readonly kind: AppRouteKind;
  readonly redirectTo?: string;
  readonly browser: BrowserVerification;
}

const CORE = { level: 'core' } as const;

/**
 * 单测将清单与 App.tsx 的叶子路由按 pattern 归一化后逐项比对，
 * 令组织顺序不影响运行时语义，新增/删除/改变守卫仍 fail closed。
 * `extended` 仅用于现有确定性服务可完整渲染、且有稳定 ready selector 的正常态。
 */
export const APP_ROUTE_MANIFEST: readonly AppRouteManifestEntry[] = [
  {
    id: 'login',
    pattern: '/login',
    samplePath: '/login',
    element: 'LoginPage',
    access: 'public',
    permission: 'anonymous',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'register',
    pattern: '/register',
    samplePath: '/register',
    element: 'RegisterPage',
    access: 'public',
    permission: 'anonymous',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="login-display-name"]' },
  },
  {
    id: 'styleguide',
    pattern: '/styleguide',
    samplePath: '/styleguide',
    element: 'StyleguidePage',
    access: 'public',
    permission: 'anonymous',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="styleguide-按钮"]' },
  },
  {
    id: 'device',
    pattern: '/device',
    samplePath: '/device',
    element: 'DeviceAuthorizationPage',
    access: 'public',
    permission: 'anonymous',
    kind: 'page',
    browser: { level: 'extended', readySelector: '#device-code', authenticated: true },
  },
  {
    id: 'forgot',
    pattern: '/forgot',
    samplePath: '/forgot',
    element: 'ForgotPasswordPage',
    access: 'public',
    permission: 'anonymous',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="forgot-email"]' },
  },
  {
    id: 'reset',
    pattern: '/reset',
    samplePath: '/reset?token=reset-fixture',
    element: 'ResetPasswordPage',
    access: 'public',
    permission: 'anonymous',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="reset-code"]' },
  },
  {
    id: 'oauth-callback',
    pattern: '/auth/oauth/callback/:provider',
    samplePath: '/auth/oauth/callback/github?code=fixture-code&state=fixture-state',
    element: 'OAuthCallbackPage',
    access: 'public',
    permission: 'anonymous',
    kind: 'page',
    browser: {
      level: 'extended',
      readySelector: '[data-testid="home-greeting"]',
      expectedPath: '/',
    },
  },
  {
    id: 'invite-accept',
    pattern: '/invite/:token',
    samplePath: '/invite/invite-fixture',
    element: 'InviteAcceptPage',
    access: 'public',
    permission: 'anonymous',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="invite-preview"]' },
  },
  {
    id: 'home',
    pattern: '/',
    samplePath: '/',
    element: 'HomePage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'forbidden',
    pattern: '/forbidden',
    samplePath: '/forbidden',
    element: 'ForbiddenPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="forbidden-page"]' },
  },
  {
    id: 'settings-index',
    pattern: '/settings',
    samplePath: '/settings',
    element: 'Navigate',
    access: 'protected',
    permission: 'authenticated',
    kind: 'redirect',
    redirectTo: 'appearance',
    browser: { level: 'redirect', expectedPath: '/settings/appearance' },
  },
  {
    id: 'settings-appearance',
    pattern: '/settings/appearance',
    samplePath: '/settings/appearance',
    element: 'AppearanceSettingsSection',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'settings-notifications',
    pattern: '/settings/notifications',
    samplePath: '/settings/notifications',
    element: 'NotificationPreferencesSection',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="notification-prefs"]' },
  },
  {
    id: 'settings-security',
    pattern: '/settings/security',
    samplePath: '/settings/security',
    element: 'SecuritySettingsSection',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="session-session-fixture"]' },
  },
  {
    id: 'workspace-picker',
    pattern: '/workspace-picker',
    samplePath: '/workspace-picker',
    element: 'WorkspacePickerPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="workspace-picker"]' },
  },
  {
    id: 'workspace-home',
    pattern: '/w/:workspaceSlug',
    samplePath: '/w/acme',
    element: 'WorkspaceHomePage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="ws-home-name"]' },
  },
  {
    id: 'workspace-settings-index',
    pattern: '/w/:workspaceSlug/settings',
    samplePath: '/w/acme/settings',
    element: 'Navigate',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'redirect',
    redirectTo: 'general',
    browser: { level: 'redirect', expectedPath: '/w/acme/settings/general' },
  },
  {
    id: 'workspace-settings-general',
    pattern: '/w/:workspaceSlug/settings/general',
    samplePath: '/w/acme/settings/general',
    element: 'WorkspaceGeneralSection',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="ws-basic-info"]' },
  },
  {
    id: 'workspace-settings-invitations',
    pattern: '/w/:workspaceSlug/settings/invitations',
    samplePath: '/w/acme/settings/invitations',
    element: 'WorkspaceInvitationsSection',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="invitation-list"]' },
  },
  {
    id: 'workspace-settings-roles',
    pattern: '/w/:workspaceSlug/settings/roles',
    samplePath: '/w/acme/settings/roles',
    element: 'WorkspaceRolesSection',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="roles-roster"]' },
  },
  {
    id: 'workspace-settings-labels',
    pattern: '/w/:workspaceSlug/settings/labels',
    samplePath: '/w/acme/settings/labels',
    element: 'WorkspaceLabelsSection',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="labels-list"]' },
  },
  {
    id: 'workspace-settings-custom-fields',
    pattern: '/w/:workspaceSlug/settings/custom-fields',
    samplePath: '/w/acme/settings/custom-fields',
    element: 'WorkspaceCustomFieldsSection',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="fields-list"]' },
  },
  {
    id: 'workspace-settings-data',
    pattern: '/w/:workspaceSlug/settings/data',
    samplePath: '/w/acme/settings/data',
    element: 'WorkspaceDataSection',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="job-row-data-job-fixture"]' },
  },
  {
    id: 'workspace-settings-tokens',
    pattern: '/w/:workspaceSlug/settings/tokens',
    samplePath: '/w/acme/settings/tokens',
    element: 'WorkspaceTokensSection',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="token-token-fixture"]' },
  },
  {
    id: 'workspace-settings-audit',
    pattern: '/w/:workspaceSlug/settings/audit',
    samplePath: '/w/acme/settings/audit',
    element: 'WorkspaceAuditSection',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="audit-audit-fixture"]' },
  },
  {
    id: 'workspace-settings-danger',
    pattern: '/w/:workspaceSlug/settings/danger',
    samplePath: '/w/acme/settings/danger',
    element: 'WorkspaceDangerSection',
    access: 'protected',
    permission: 'workspace_owner',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="danger-zone"]' },
  },
  {
    id: 'workspace-settings-members',
    pattern: '/w/:workspaceSlug/settings/members',
    samplePath: '/w/acme/settings/members',
    element: 'WorkspaceMembersSettingsPage',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="ws-settings-members"]' },
  },
  {
    id: 'workspace-settings-approvals',
    pattern: '/w/:workspaceSlug/settings/approvals',
    samplePath: '/w/acme/settings/approvals',
    element: 'WorkspaceApprovalsSettingsPage',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="ws-settings-approvals"]' },
  },
  {
    id: 'workspace-settings-fields',
    pattern: '/w/:workspaceSlug/settings/fields',
    samplePath: '/w/acme/settings/fields',
    element: 'WorkspaceFieldsSettingsPage',
    access: 'protected',
    permission: 'workspace_admin',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="ws-settings-fields"]' },
  },
  {
    id: 'approvals',
    pattern: '/approvals',
    samplePath: '/approvals',
    element: 'ApprovalsPage',
    access: 'protected',
    permission: 'human',
    kind: 'page',
    browser: { level: 'extended', readySelector: '.mesh-approvals .mesh-empty-state' },
  },
  {
    id: 'workspace-approvals',
    pattern: '/w/:workspaceSlug/approvals',
    samplePath: '/w/acme/approvals',
    element: 'ApprovalsPage',
    access: 'protected',
    permission: 'human',
    kind: 'page',
    browser: { level: 'extended', readySelector: '.mesh-approvals .mesh-empty-state' },
  },
  {
    id: 'inbox',
    pattern: '/w/:workspaceSlug/inbox',
    samplePath: '/w/acme/inbox',
    element: 'InboxPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'inbox-detail',
    pattern: '/w/:workspaceSlug/inbox/:notificationId',
    samplePath: '/w/acme/inbox/n-1',
    element: 'InboxPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="inbox-preview"]' },
  },
  {
    id: 'projects',
    pattern: '/w/:workspaceSlug/projects',
    samplePath: '/w/acme/projects',
    element: 'ProjectsPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="projects-table"]' },
  },
  {
    id: 'project-detail',
    pattern: '/w/:workspaceSlug/projects/:projectId',
    samplePath: '/w/acme/projects/project-1',
    element: 'ProjectDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="project-detail-header"]' },
  },
  {
    id: 'project-settings',
    pattern: '/w/:workspaceSlug/projects/:projectId/settings',
    samplePath: '/w/acme/projects/project-1/settings',
    element: 'ProjectSettingsPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="settings-form"]' },
  },
  {
    id: 'issues',
    pattern: '/w/:workspaceSlug/issues',
    samplePath: '/w/acme/issues',
    element: 'IssuesPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'workspace-issue-identifier',
    pattern: '/w/:workspaceSlug/issues/by-identifier/:identifier',
    samplePath: '/w/acme/issues/by-identifier/MESH-1',
    element: 'WorkspaceIssueByIdentifierRedirect',
    access: 'protected',
    permission: 'authenticated',
    kind: 'resolver_redirect',
    browser: {
      level: 'extended',
      readySelector: '[data-testid="issue-detail"]',
      expectedPath: '/w/acme/issues/0d3a1f7c-9b2e-4c5a-8f1d-6e7b8c9a0d1e',
    },
  },
  {
    id: 'issue-detail',
    pattern: '/w/:workspaceSlug/issues/:issueId',
    samplePath: '/w/acme/issues/0d3a1f7c-9b2e-4c5a-8f1d-6e7b8c9a0d1e',
    element: 'IssueByIdRedirect',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'board',
    pattern: '/w/:workspaceSlug/board',
    samplePath: '/w/acme/board',
    element: 'BoardPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'view-board',
    pattern: '/w/:workspaceSlug/views/:viewId',
    samplePath: '/w/acme/views/view-1',
    element: 'BoardPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="board-card-issue-1"]' },
  },
  {
    id: 'members',
    pattern: '/w/:workspaceSlug/members',
    samplePath: '/w/acme/members',
    element: 'MembersPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'member-detail',
    pattern: '/w/:workspaceSlug/members/:memberId',
    samplePath: '/w/acme/members/member-human-1',
    element: 'MemberDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="member-detail"]' },
  },
  {
    id: 'agent-detail',
    pattern: '/w/:workspaceSlug/agents/:agentId',
    samplePath: '/w/acme/agents/agent-1',
    element: 'AgentDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="agent-detail-page"]' },
  },
  {
    id: 'squads',
    pattern: '/w/:workspaceSlug/squads',
    samplePath: '/w/acme/squads',
    element: 'SquadsPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="squad-grid"]' },
  },
  {
    id: 'squad-detail',
    pattern: '/w/:workspaceSlug/squads/:squadId',
    samplePath: '/w/acme/squads/squad-1',
    element: 'SquadDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="squad-detail-page"]' },
  },
  {
    id: 'squad-task-detail',
    pattern: '/w/:workspaceSlug/squads/:squadId/tasks/:taskId',
    samplePath: '/w/acme/squads/squad-1/tasks/task-1',
    element: 'SquadTaskDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="squad-task-page"]' },
  },
  {
    id: 'cycles',
    pattern: '/w/:workspaceSlug/cycles',
    samplePath: '/w/acme/cycles',
    element: 'CyclesPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="cycle-list"]' },
  },
  {
    id: 'skills',
    pattern: '/w/:workspaceSlug/automations/skills',
    samplePath: '/w/acme/automations/skills',
    element: 'SkillsPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="skills-grid"]' },
  },
  {
    id: 'skills-marketplace',
    pattern: '/w/:workspaceSlug/automations/skills/marketplace',
    samplePath: '/w/acme/automations/skills/marketplace',
    element: 'MarketplacePage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="marketplace-grid"]' },
  },
  {
    id: 'skill-detail',
    pattern: '/w/:workspaceSlug/automations/skills/:skillId',
    samplePath: '/w/acme/automations/skills/skill-1',
    element: 'SkillDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="skill-detail"]' },
  },
  {
    id: 'legacy-marketplace',
    pattern: '/marketplace',
    samplePath: '/marketplace',
    element: 'Navigate',
    access: 'protected',
    permission: 'authenticated',
    kind: 'redirect',
    redirectTo: '/skills/marketplace',
    browser: {
      level: 'redirect',
      expectedPath: '/w/acme/automations/skills/marketplace',
    },
  },
  {
    id: 'chat',
    pattern: '/w/:workspaceSlug/chat',
    samplePath: '/w/acme/chat',
    element: 'ChatPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'chat-session',
    pattern: '/w/:workspaceSlug/chat/:sessionId',
    samplePath: '/w/acme/chat/sess-1',
    element: 'ChatPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="chat-messages"]' },
  },
  {
    id: 'runtimes',
    pattern: '/w/:workspaceSlug/automations/runtimes',
    samplePath: '/w/acme/automations/runtimes',
    element: 'RuntimesPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="runtimes-table"]' },
  },
  {
    id: 'runtime-detail',
    pattern: '/w/:workspaceSlug/automations/runtimes/:runtimeId',
    samplePath: '/w/acme/automations/runtimes/runtime-1',
    element: 'RuntimeDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="runtime-inflight-list"]' },
  },
  {
    id: 'execution-detail',
    pattern: '/w/:workspaceSlug/executions/:executionId',
    samplePath: '/w/acme/executions/exec-1',
    element: 'ExecutionDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'autopilots',
    pattern: '/w/:workspaceSlug/automations/autopilots',
    samplePath: '/w/acme/automations/autopilots',
    element: 'AutopilotsPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'insights',
    pattern: '/w/:workspaceSlug/insights',
    samplePath: '/w/acme/insights',
    element: 'InsightsPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'autopilot-new',
    pattern: '/w/:workspaceSlug/automations/autopilots/new',
    samplePath: '/w/acme/automations/autopilots/new',
    element: 'AutopilotEditorPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: {
      level: 'extended',
      readySelector: '[data-testid="autopilot-schedule-preview"]',
    },
  },
  {
    id: 'autopilot-run',
    pattern: '/w/:workspaceSlug/automations/autopilots/runs/:runId',
    samplePath: '/w/acme/automations/autopilots/runs/run-1',
    element: 'AutopilotRunDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="autopilot-run-attempts"]' },
  },
  {
    id: 'autopilot-detail',
    pattern: '/w/:workspaceSlug/automations/autopilots/:autopilotId',
    samplePath: '/w/acme/automations/autopilots/autopilot-1',
    element: 'AutopilotDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="autopilot-runs-table"]' },
  },
  {
    id: 'autopilot-edit',
    pattern: '/w/:workspaceSlug/automations/autopilots/:autopilotId/edit',
    samplePath: '/w/acme/automations/autopilots/autopilot-1/edit',
    element: 'AutopilotEditorPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: {
      level: 'extended',
      readySelector: '[data-testid="autopilot-schedule-preview"]',
    },
  },
  {
    id: 'incoming-webhooks',
    pattern: '/w/:workspaceSlug/automations/webhooks',
    samplePath: '/w/acme/automations/webhooks',
    element: 'WebhookConfigPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="webhook-events-table"]' },
  },
  {
    id: 'integrations',
    pattern: '/w/:workspaceSlug/automations/integrations',
    samplePath: '/w/acme/automations/integrations',
    element: 'IntegrationsPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: CORE,
  },
  {
    id: 'integration-detail',
    pattern: '/w/:workspaceSlug/automations/integrations/:integrationId',
    samplePath: '/w/acme/automations/integrations/integration-1',
    element: 'IntegrationDetailPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="integration-overview"]' },
  },
  {
    id: 'webhook-subscriptions',
    pattern: '/w/:workspaceSlug/automations/webhook-subscriptions',
    samplePath: '/w/acme/automations/webhook-subscriptions',
    element: 'WebhooksPage',
    access: 'protected',
    permission: 'authenticated',
    kind: 'page',
    browser: { level: 'extended', readySelector: '[data-testid="webhook-card-subscription-1"]' },
  },
  {
    id: 'legacy-automation',
    pattern: '/automation',
    samplePath: '/automation',
    element: 'Navigate',
    access: 'protected',
    permission: 'authenticated',
    kind: 'redirect',
    redirectTo: '/autopilots',
    browser: {
      level: 'redirect',
      expectedPath: '/w/acme/automations/autopilots',
    },
  },
  {
    id: 'flat-route-migration',
    pattern: '*',
    samplePath: '/route-manifest-not-found',
    element: 'FlatRouteMigration',
    access: 'protected',
    permission: 'authenticated',
    kind: 'not_found',
    browser: { level: 'extended', readySelector: '[data-testid="notfound-home"]' },
  },
];
