FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml README.md requirements-dev.lock ./
RUN pip install --no-cache-dir -r requirements-dev.lock

COPY src ./src
COPY migrations ./migrations
COPY tests ./tests
COPY alembic.ini ./

RUN pip install --no-cache-dir --no-deps -e . \
    && pip check

CMD ["python", "-m", "pytest"]
