#!/usr/bin/env bash
# MES-106 验收栈环境生成器:强随机凭据 + 固定回环端口 → stack.env(不入库)。
#
# 复现 issue 场景:production 鉴权 + 公网 HTTP(MESH_SESSION_COOKIE_SECURE=false),
# 前端同源构建(Dockerfile 空 VITE_MESH_*),手机端宽度由 Playwright 配置模拟。
#
#   ./frontend/e2e/mes106/gen-stack-env.sh            # 首次生成
#   ./frontend/e2e/mes106/gen-stack-env.sh --force    # 轮换全部凭据
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${DIR}/stack.env"

if [[ -e "${ENV_FILE}" && "${1:-}" != "--force" ]]; then
  echo "stack.env already exists — leaving it untouched (--force to regenerate)." >&2
  exit 1
fi

gen_secret() {
  openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n'
}

umask 077
cat > "${ENV_FILE}" <<EOF
# MES-106 e2e stack — generated by gen-stack-env.sh. Strong random values,
# local only. NEVER commit this file.

# Datastore credentials (compose refuses to start without them)
MESH_POSTGRES_DB=mesh
MESH_POSTGRES_USER=mesh
MESH_POSTGRES_PASSWORD=$(gen_secret)
MESH_REDIS_PASSWORD=$(gen_secret)
MESH_APP_DB_PASSWORD=$(gen_secret)
MESH_STORAGE_ACCESS_KEY=$(gen_secret)
MESH_STORAGE_SECRET_KEY=$(gen_secret)

# Production auth signing / pepper keys (auth_mode=production fails closed without)
MESH_JWT_SECRET=$(gen_secret)
MESH_DEVICE_CODE_PEPPER=$(gen_secret)

# Reproduce the issue scenario: production auth over plain HTTP
MESH_AUTH_MODE=production
MESH_SESSION_COOKIE_SECURE=false

# Loopback-bound fixed ports (avoid clashing with other local stacks)
MESH_API_PORT=18300
MESH_WS_PORT=18301
MESH_FRONTEND_PORT=18310
MESH_STORAGE_PORT=19000
MESH_STORAGE_CONSOLE_PORT=19001
MESH_STORAGE_PUBLIC_ENDPOINT=http://127.0.0.1:19000
EOF

echo "Wrote ${ENV_FILE} (mode $(stat -c '%a' "${ENV_FILE}" 2>/dev/null || stat -f '%Lp' "${ENV_FILE}"))."
