"""M1/L4 acceptance: mesh_app RLS is live on the issue 五表.

The API/gateway connect as ``mesh_app`` (non-owner). These tests connect as
that exact role against real PostgreSQL 16 and prove the RLS backstop on the
issue tables (issues / issue_statuses / issue_dependencies / issue_activity /
issue_templates — policies generated by migration 0009 from the same template
as the realtime tables covered by test_app_role_rls_e2e.py):

* an unset ``mesh.workspace_id`` GUC fails closed on every table — pinned
  to the ``undefined_object`` sqlstate, not just any statement error;
* with the GUC set, only the named tenant's rows are visible;
* a cross-tenant INSERT is rejected — pinned to the RLS-policy sqlstate so
  the write path is proven fail-closed (not merely errored).
"""

from __future__ import annotations

import uuid

import pytest
import pytest_asyncio
from sqlalchemy import text
from sqlalchemy.exc import DBAPIError
from sqlalchemy.ext.asyncio import create_async_engine

from mesh.db.models.issue import (
    Issue,
    IssueActivity,
    IssueDependency,
    IssueStatus,
    IssueTemplate,
)
from mesh.db.models.member import Member
from tests.e2e.conftest import _app_role_url

pytestmark = pytest.mark.e2e

# table → rows seeded per workspace by _seed()
SEEDED_COUNTS = {
    "issues": 2,
    "issue_statuses": 2,
    "issue_dependencies": 1,
    "issue_activity": 1,
    "issue_templates": 1,
}

# PG SQLSTATEs that anchor the fail-closed semantics: assertions pin these
# rather than a bare DBAPIError so unrelated statement errors (missing
# GRANT, FK failure, …) can never satisfy the tests by accident.
SQLSTATE_UNDEFINED_OBJECT = "42704"  # current_setting() on the unset GUC
SQLSTATE_RLS_REJECTION = "42501"  # policy WITH CHECK rejects the write


@pytest_asyncio.fixture
async def app_role_engine(db_url):
    """An engine connected as the restricted app role the API/gateway use."""
    engine = create_async_engine(_app_role_url(db_url))
    yield engine
    await engine.dispose()


async def _seed(session_factory, workspace_id, tag: str) -> uuid.UUID:
    """Seed one connected row-set of all five tables (owner connection)."""
    async with session_factory() as session, session.begin():
        from mesh.db.models.agent import Agent
        from mesh.db.models.user import User

        # Agent roster rows reference a real agents row (composite FK); the
        # agent needs a human owner (agents.owner_user_id NOT NULL).
        agent_owner = User(
            email=f"{uuid.uuid4().hex[:12]}@corp.com",
            password_hash="x",
            display_name="Agent Owner",
        )
        session.add(agent_owner)
        await session.flush()
        agent_row = Agent(
            workspace_id=workspace_id,
            name=f"RLS Agent {tag}",
            owner_user_id=agent_owner.id,
        )
        session.add(agent_row)
        await session.flush()
        actor = Member(
            workspace_id=workspace_id,
            member_type="agent",
            agent_id=agent_row.id,
            role="member",
        )
        session.add(actor)
        await session.flush()
        todo = IssueStatus(
            workspace_id=workspace_id, name=f"Todo {tag}", category="todo", position=0.0
        )
        doing = IssueStatus(
            workspace_id=workspace_id,
            name=f"Doing {tag}",
            category="in_progress",
            position=1.0,
        )
        session.add_all([todo, doing])
        await session.flush()
        first = Issue(
            workspace_id=workspace_id,
            identifier_namespace_key=tag,
            number=1,
            identifier=f"{tag}-1",
            title=f"one {tag}",
            status_id=todo.id,
            state_category="todo",
        )
        second = Issue(
            workspace_id=workspace_id,
            identifier_namespace_key=tag,
            number=2,
            identifier=f"{tag}-2",
            title=f"two {tag}",
            status_id=todo.id,
            state_category="todo",
        )
        session.add_all([first, second])
        await session.flush()
        session.add(
            IssueDependency(
                workspace_id=workspace_id, issue_id=first.id, depends_on_id=second.id
            )
        )
        session.add(IssueActivity(workspace_id=workspace_id, issue_id=first.id, field="title"))
        session.add(
            IssueTemplate(
                workspace_id=workspace_id,
                name=f"tmpl {tag}",
                template_body={"title": "x"},
                created_by=actor.id,
            )
        )
    return actor.id


async def test_app_role_issue_tables_fail_closed_without_guc(app_role_engine):
    for table in SEEDED_COUNTS:
        # Fresh connection per probe: the first policy failure aborts the
        # implicit transaction, and a reused connection would answer every
        # later statement with in_failed_sql_transaction (25P02) instead of
        # proving the per-table fail-closed error.
        async with app_role_engine.connect() as conn:
            # Without the GUC the policy's current_setting() cannot even be
            # evaluated → undefined_object, NOT just "some statement error":
            # pin the sqlstate so a missing GRANT or table could never
            # satisfy this assertion by accident.
            with pytest.raises(DBAPIError) as excinfo:
                await conn.execute(text(f"SELECT count(*) FROM {table}"))
            orig = excinfo.value.orig
            assert orig.sqlstate == SQLSTATE_UNDEFINED_OBJECT
            assert "mesh.workspace_id" in str(orig)


async def test_app_role_issue_tables_cross_tenant_hidden_with_guc(
    app_role_engine, session_factory, workspace_factory
):
    ws_a = await workspace_factory(name="A", slug=f"rls-ia-{uuid.uuid4().hex[:8]}")
    ws_b = await workspace_factory(name="B", slug=f"rls-ib-{uuid.uuid4().hex[:8]}")
    await _seed(session_factory, ws_a.id, "A")
    await _seed(session_factory, ws_b.id, "B")

    async with app_role_engine.connect() as conn:
        async with conn.begin():
            await conn.execute(
                text("SELECT set_config('mesh.workspace_id', :ws, true)"),
                {"ws": str(ws_a.id)},
            )
            counts = {}
            for table in SEEDED_COUNTS:
                counts[table] = (
                    await conn.execute(text(f"SELECT count(*) FROM {table}"))
                ).scalar_one()

    # Only tenant A's rows are visible on the app path — tenant B is hidden.
    assert counts == SEEDED_COUNTS


async def test_app_role_issue_tables_cross_tenant_insert_rejected(
    app_role_engine, session_factory, workspace_factory
):
    ws_a = await workspace_factory(name="A", slug=f"rls-wa-{uuid.uuid4().hex[:8]}")
    ws_b = await workspace_factory(name="B", slug=f"rls-wb-{uuid.uuid4().hex[:8]}")
    actor_b = await _seed(session_factory, ws_b.id, "B")

    async with app_role_engine.connect() as conn:
        async with conn.begin():
            # GUC names tenant A; the row targets tenant B → the policy's
            # WITH CHECK (USING) fails closed on the write path too.
            await conn.execute(
                text("SELECT set_config('mesh.workspace_id', :ws, true)"),
                {"ws": str(ws_a.id)},
            )
            with pytest.raises(DBAPIError) as excinfo:
                await conn.execute(
                    text(
                        "INSERT INTO issue_templates "
                        "(workspace_id, name, template_body, created_by) "
                        "VALUES (:ws, 'x', '{}', :by)"
                    ),
                    {"ws": ws_b.id, "by": actor_b},
                )
            # Pin the RLS rejection itself (insufficient_privilege from the
            # policy WITH CHECK), not merely "a statement error" — a GRANT
            # denial or FK failure must not satisfy this test by accident.
            orig = excinfo.value.orig
            assert orig.sqlstate == SQLSTATE_RLS_REJECTION
            assert "row-level security policy" in str(orig)
