#!/usr/bin/env bash
# Mesh local development secret generator (MES-83 hardening).
#
# docker-compose.yml carries NO default secrets — every credential is a required
# variable (`${VAR:?...}`), so the stack refuses to start on a guessable
# password. For LOCAL DEVELOPMENT, run this script ONCE to generate a `.env`
# with strong, random, per-checkout values:
#
#     ./scripts/gen-dev-secrets.sh
#     docker compose up --build -d
#
# The generated `.env` is git-ignored — it never leaves this machine. Production
# deployments must set their own strong, unique secrets (see .env.example) and
# MESH_AUTH_MODE=production; the backend additionally refuses weak credentials
# at startup in production mode.
#
# Flags:
#   --force   overwrite an existing .env (a new random set is generated)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

if [[ -e "${ENV_FILE}" && "${1:-}" != "--force" ]]; then
  echo ".env already exists — leaving it untouched." >&2
  echo "Re-run with --force to regenerate (this rotates every secret)." >&2
  exit 1
fi

# Strong random secret: 32 bytes of CSPRNG output, URL-safe base64, no padding
# characters that would need escaping inside connection URLs.
gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n'
  else
    python3 -c 'import secrets; print(secrets.token_urlsafe(32), end="")'
  fi
}

POSTGRES_PASSWORD="$(gen_secret)"
REDIS_PASSWORD="$(gen_secret)"
APP_DB_PASSWORD="$(gen_secret)"
STORAGE_ACCESS_KEY="$(gen_secret)"
STORAGE_SECRET_KEY="$(gen_secret)"
JWT_SECRET="$(gen_secret)"
SEARCH_CURSOR_SECRET="$(gen_secret)"
DEVICE_CODE_PEPPER="$(gen_secret)"

# umask so the file is created owner-read/write only — it holds live secrets.
umask 077
cat > "${ENV_FILE}" <<EOF
# Mesh LOCAL DEVELOPMENT environment — generated by scripts/gen-dev-secrets.sh.
# Strong random values, unique to this checkout. NEVER commit this file, and
# never reuse these values in a shared or production deployment.
# Regenerate with: ./scripts/gen-dev-secrets.sh --force

# PostgreSQL (docker compose service credentials)
MESH_POSTGRES_DB=mesh
MESH_POSTGRES_USER=mesh
MESH_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis requirepass + the credential in every MESH_REDIS_URL.
MESH_REDIS_PASSWORD=${REDIS_PASSWORD}

# Restricted non-owner DB role password for the API/gateway app connection.
MESH_APP_DB_PASSWORD=${APP_DB_PASSWORD}

# Object storage (MinIO) root credentials.
MESH_STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}
MESH_STORAGE_SECRET_KEY=${STORAGE_SECRET_KEY}

# JWT signing secret (also derives the at-rest MFA encryption key).
MESH_JWT_SECRET=${JWT_SECRET}

# Search cursor HMAC key (search-command-palette.md §3.2): the api factory
# refuses the public dev key at startup in production mode.
MESH_SEARCH_CURSOR_SECRET=${SEARCH_CURSOR_SECRET}

# Device-code HMAC pepper (auth.md §2.4.2): the low-entropy user_code space
# must never be keyed by a public value; production fails closed without it.
MESH_DEVICE_CODE_PEPPER=${DEVICE_CODE_PEPPER}

# Local development auth mode (safe ONLY while ports stay loopback-bound).
MESH_AUTH_MODE=dev

# Absolute browser origin for email and external approval-card deep links.
MESH_APP_BASE_URL=http://127.0.0.1:8000
EOF

echo "Wrote ${ENV_FILE} (mode $(stat -c '%a' "${ENV_FILE}" 2>/dev/null || stat -f '%Lp' "${ENV_FILE}"))."
echo "Next: docker compose up --build -d"
