#!/usr/bin/env bash
# MES-111 批次④ 验收栈环境生成器:强随机凭据 + 固定回环端口 → stack.env(不入库)。
#
# production 鉴权 + 公网 HTTP 形态(MESH_SESSION_COOKIE_SECURE=false),前端同源构建。
# 端口段 18340/18341/18350(与 mes106/mes107 的 18300/18320 段错开,并行不冲突)。
#
#   ./frontend/e2e/mes111-b4/gen-stack-env.sh            # 首次生成
#   ./frontend/e2e/mes111-b4/gen-stack-env.sh --force    # 轮换全部凭据
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${DIR}/stack.env"

if [[ -e "${ENV_FILE}" && "${1:-}" != "--force" ]]; then
  echo "stack.env already exists — leaving it untouched (--force to regenerate)." >&2
  exit 1
fi

gen_secret() {
  openssl rand -base64 32 | tr '+/' '-_' | tr -d '=\n'
}

umask 077
cat > "${ENV_FILE}" <<EOF
# MES-111 batch 4 e2e stack — generated by gen-stack-env.sh. Strong random
# values, local loopback only. NEVER commit this file.

# Datastore credentials (compose refuses to start without them)
MESH_POSTGRES_DB=mesh
MESH_POSTGRES_USER=mesh
MESH_POSTGRES_PASSWORD=$(gen_secret)
MESH_REDIS_PASSWORD=$(gen_secret)
MESH_APP_DB_PASSWORD=$(gen_secret)
MESH_STORAGE_ACCESS_KEY=$(gen_secret)
MESH_STORAGE_SECRET_KEY=$(gen_secret)

# Production auth signing / pepper keys (auth_mode=production fails closed without)
MESH_JWT_SECRET=$(gen_secret)
MESH_DEVICE_CODE_PEPPER=$(gen_secret)

# Reproduce the production scenario over plain HTTP
MESH_AUTH_MODE=production
MESH_SESSION_COOKIE_SECURE=false

# Loopback-bound fixed ports (distinct from other local stacks)
MESH_API_PORT=18340
MESH_WS_PORT=18341
MESH_FRONTEND_PORT=18350
MESH_STORAGE_PORT=19020
MESH_STORAGE_CONSOLE_PORT=19021
MESH_STORAGE_PUBLIC_ENDPOINT=http://127.0.0.1:19020
EOF

echo "Wrote ${ENV_FILE} (mode $(stat -c '%a' "${ENV_FILE}" 2>/dev/null || stat -f '%Lp' "${ENV_FILE}"))."
